import { createContext, useContext, useState, type CSSProperties, type FormEvent, type ReactNode } from 'react';
import { Link, NavLink, Outlet, Route, Routes, useNavigate } from 'react-router-dom';
import { BarChart3, BookOpen, Check, ChevronDown, ClipboardCheck, Copy, FileText, GraduationCap, HelpCircle, LayoutDashboard, Menu, Plus, Printer, Save, Settings, ShieldCheck, Sparkles, X } from 'lucide-react';
import { sectionTitles } from './data/checklist';
import { listLocalReviews, saveLocalReview, saveReviewerDecision, saveSubmission } from './services/apiClient';
import { runLocalReview } from './services/localReviewEngine';
import { copyReportSummary } from './services/reportService';
import type { ItemResult, ReviewResult, SubmissionInput } from './types';

type ReviewContextType = { current?: ReviewResult; setCurrent: (value?: ReviewResult) => void; reviews: ReviewResult[]; refresh: () => void };
const ReviewContext = createContext<ReviewContextType | null>(null);
const useReviews = () => useContext(ReviewContext)!;
const today = new Date().toISOString().slice(0, 10);
const initialForm: SubmissionInput = { studentName:'', matricNo:'', programme:'', thesisTitle:'', supervisorName:'', examinerName:'', reviewDate:today, thesisLanguage:'English', englishAbstract:'', malayAbstract:'' };

function App() {
  const [current, setCurrent] = useState<ReviewResult>();
  const [reviews, setReviews] = useState(() => listLocalReviews());
  const refresh = () => setReviews(listLocalReviews());
  return <ReviewContext.Provider value={{ current, setCurrent, reviews, refresh }}><Routes><Route element={<Shell />}><Route index element={<Landing />} /><Route path="new" element={<NewReview />} /><Route path="results" element={<Results />} /><Route path="dashboard" element={<Dashboard />} /><Route path="report" element={<Report />} /><Route path="settings" element={<SettingsPage />} /><Route path="help" element={<Help />} /></Route></Routes></ReviewContext.Provider>;
}

function Shell() {
  const [open, setOpen] = useState(false);
  const links = [
    ['/', LayoutDashboard, 'Overview'], ['/dashboard', BarChart3, 'Dashboard'], ['/new', Plus, 'New review'],
    ['/results', ClipboardCheck, 'Review results'], ['/report', FileText, 'Reports'], ['/settings', Settings, 'Settings'], ['/help', HelpCircle, 'Help']
  ] as const;
  return <div className="app-shell">
    <aside className={open ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><span className="brand-mark"><GraduationCap size={22}/></span><span><strong>FC Abstract</strong><small>Review Assistant</small></span></div>
      <nav aria-label="Main navigation">{links.map(([to, Icon, label]) => <NavLink end={to === '/'} key={to} to={to} onClick={() => setOpen(false)}><Icon size={18}/>{label}</NavLink>)}</nav>
      <div className="sidebar-note"><ShieldCheck size={20}/><div><strong>Human-led review</strong><small>Automated checks assist, never approve.</small></div></div>
    </aside>
    <div className="main-column">
      <header><button className="icon-button mobile-menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><Menu/></button><div><strong>Faculty of Computing</strong><span>Academic quality review workspace</span></div><span className="status-pill"><i/> Local checks ready</span></header>
      <main><Outlet /></main>
    </div>
  </div>;
}

function Landing() {
  const { reviews } = useReviews();
  return <div className="landing">
    <section className="hero">
      <div><span className="eyebrow"><Sparkles size={15}/> Faculty guideline-aligned</span><h1>Stronger abstracts.<br/><em>Clearer research.</em></h1><p>Review bilingual thesis abstracts against the official Faculty of Computing guideline and checklist—quickly, consistently, and with human judgment kept in control.</p><div className="button-row"><Link className="button primary" to="/new">Start new review <span>→</span></Link><Link className="button secondary" to="/dashboard">View dashboard</Link></div></div>
      <div className="hero-card"><div className="paper-top"><span>Pre-check snapshot</span><span className="mini-score">86%</span></div><div className="paper-line long"/><div className="paper-line"/><div className="preview-item"><span className="check-icon"><Check size={14}/></span><div><strong>Bilingual abstracts</strong><small>Both versions provided</small></div><b>Pass</b></div><div className="preview-item"><span className="warn-icon">!</span><div><strong>Word count</strong><small>English: 318 words</small></div><b className="amber">Review</b></div><div className="preview-item"><span className="check-icon"><Check size={14}/></span><div><strong>One paragraph</strong><small>Both versions comply</small></div><b>Pass</b></div><div className="paper-footer"><span>33 checks across 6 sections</span><span>Human confirmation required</span></div></div>
    </section>
    <section className="metrics"><div><strong>{reviews.length}</strong><span>Reviews in this browser</span></div><div><strong>33</strong><span>Checklist items</span></div><div><strong>2</strong><span>Language versions</span></div><div><strong>150–300</strong><span>Words per abstract</span></div></section>
    <section className="feature-section"><div><span className="section-kicker">A careful first pass</span><h2>Everything needed before faculty review</h2></div><div className="feature-grid"><Feature icon={<BookOpen/>} title="Guideline grounded" text="Checks map directly to the approved abstract guideline and official A–F checklist."/><Feature icon={<ClipboardCheck/>} title="Instant pre-check" text="Word count, paragraphs, future tense, abbreviations and unit spacing run locally."/><Feature icon={<ShieldCheck/>} title="Reviewer in control" text="Every automated result can be confirmed, changed and explained by a reviewer."/></div></section>
  </div>;
}

function Feature({icon,title,text}:{icon:ReactNode,title:string,text:string}) { return <article className="feature-card"><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>; }

function NewReview() {
  const [form, setForm] = useState(initialForm); const [errors, setErrors] = useState<Record<string,string>>({}); const [saving, setSaving] = useState(false); const { setCurrent, refresh } = useReviews(); const navigate = useNavigate();
  const update = (key: keyof SubmissionInput, value: string) => { setForm((old) => ({...old,[key]:value})); setErrors((old) => ({...old,[key]:''})); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const next:Record<string,string> = {}; ['studentName','matricNo','programme','thesisTitle','englishAbstract','malayAbstract'].forEach((key) => { if (!String(form[key as keyof SubmissionInput]).trim()) next[key] = 'This field is required.'; }); setErrors(next); if (Object.keys(next).length) return; setSaving(true); const review = runLocalReview(form); try { const savedMeta = await saveSubmission(form, review); const saved = saveLocalReview({...review, backendSaved:savedMeta.backendSaved, syncWarning:savedMeta.warning, submission:{...form, submissionId:savedMeta.submissionId}}); setCurrent(saved); refresh(); navigate('/results'); } finally { setSaving(false); } };
  const saveDraft = () => { const draft = saveLocalReview(runLocalReview(form)); setCurrent(draft); refresh(); navigate('/dashboard'); };
  return <div className="page narrow"><PageTitle kicker="New assessment" title="Start an abstract review" text="Enter thesis details and both language versions. Requirements trigger warnings, not submission blocks."/>
    <form onSubmit={submit} className="form-stack">
      <FormSection number="01" title="Student & thesis details" text="Information used in the official review record."><div className="form-grid"><Field label="Student name" value={form.studentName} error={errors.studentName} onChange={(v)=>update('studentName',v)}/><Field label="Matric no." value={form.matricNo} error={errors.matricNo} onChange={(v)=>update('matricNo',v)}/><Field label="Programme" value={form.programme} error={errors.programme} onChange={(v)=>update('programme',v)} placeholder="e.g. Master of Computer Science"/><Field label="Review date" type="date" value={form.reviewDate} onChange={(v)=>update('reviewDate',v)}/><Field wide label="Thesis title" value={form.thesisTitle} error={errors.thesisTitle} onChange={(v)=>update('thesisTitle',v)}/><Field label="Supervisor name" value={form.supervisorName} onChange={(v)=>update('supervisorName',v)}/><Field label="Examiner name" value={form.examinerName} onChange={(v)=>update('examinerName',v)}/></div></FormSection>
      <FormSection number="02" title="Language order" text="The generated report follows the thesis language."><div className="choice-row">{(['English','Bahasa Melayu'] as const).map((language)=><label className={form.thesisLanguage===language?'choice selected':'choice'} key={language}><input type="radio" name="language" checked={form.thesisLanguage===language} onChange={()=>update('thesisLanguage',language)}/><span><strong>{language}</strong><small>{language==='English'?'English first, then Bahasa Melayu':'Bahasa Melayu first, then English'}</small></span></label>)}</div></FormSection>
      <FormSection number="03" title="Bilingual abstracts" text="Paste each abstract as one continuous paragraph."><AbstractBox label="English abstract" lang="EN" value={form.englishAbstract} error={errors.englishAbstract} onChange={(v)=>update('englishAbstract',v)}/><AbstractBox label="Abstrak Bahasa Melayu" lang="BM" value={form.malayAbstract} error={errors.malayAbstract} onChange={(v)=>update('malayAbstract',v)}/></FormSection>
      <div className="form-actions"><button type="button" className="button secondary" onClick={saveDraft}><Save size={17}/> Save draft</button><button className="button primary" disabled={saving}>{saving?'Checking…':'Run pre-check'} <span>→</span></button></div>
    </form>
  </div>;
}

function PageTitle({kicker,title,text,actions}:{kicker:string,title:string,text:string,actions?:ReactNode}) { return <div className="page-title"><div><span className="section-kicker">{kicker}</span><h1>{title}</h1><p>{text}</p></div>{actions}</div>; }
function FormSection({number,title,text,children}:{number:string,title:string,text:string,children:ReactNode}) { return <section className="form-section"><div className="form-section-title"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>; }
function Field({label,value,onChange,error,placeholder,type='text',wide=false}:{label:string,value:string,onChange:(v:string)=>void,error?:string,placeholder?:string,type?:string,wide?:boolean}) { return <label className={wide?'field wide':'field'}><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(e)=>onChange(e.target.value)} aria-invalid={!!error}/>{error&&<small className="error">{error}</small>}</label>; }
function AbstractBox({label,lang,value,onChange,error}:{label:string,lang:string,value:string,onChange:(v:string)=>void,error?:string}) { const words=value.trim()?value.trim().split(/\s+/).length:0; return <label className="abstract-box"><span className="abstract-label"><span><b>{lang}</b><strong>{label}</strong></span><small className={words>300?'over':''}>{words} / 300 words</small></span><textarea rows={9} value={value} onChange={(e)=>onChange(e.target.value)} placeholder={`Paste the ${label.toLowerCase()} here…`} aria-invalid={!!error}/>{error&&<small className="error">{error}</small>}</label>; }

function Results() {
  const { current, setCurrent, refresh } = useReviews(); const navigate=useNavigate(); const [openSections,setOpenSections]=useState<string[]>(['A','B']);
  if (!current) return <EmptyState title="No active review" text="Start a new review or open one from the dashboard."/>;
  const counts = ['Yes','No','Needs Review'].map((status)=>current.items.filter((i)=>(i.reviewerResult||i.autoResult)===status).length);
  const updateItem=(code:string,result:ItemResult)=>{ const updated={...current,items:current.items.map((i)=>i.itemCode===code?{...i,reviewerResult:result,source:'reviewer' as const}:i)}; setCurrent(updated); saveLocalReview(updated); refresh(); };
  return <div className="page"><PageTitle kicker="Pre-check complete" title="Review results" text={`${current.submission.studentName} · ${current.submission.matricNo}`} actions={<button className="button primary" onClick={()=>navigate('/report')}>Prepare decision <span>→</span></button>}/>
    {current.syncWarning&&<div className="sync-banner" role="status"><span>!</span><div><strong>Google sync pending</strong><p>{current.syncWarning}</p></div></div>}
    <div className="summary-grid"><div className="score-card"><div className="score-ring" style={{'--score':`${current.score*3.6}deg`} as CSSProperties}><span><strong>{current.score}%</strong><small>decisive checks</small></span></div><div><span className="eyebrow">Compliance snapshot</span><h2>Reviewer attention needed</h2><p>{counts[2]} items require academic judgment before a final decision.</p></div></div><div className="summary-stat yes"><strong>{counts[0]}</strong><span>Passed</span></div><div className="summary-stat no"><strong>{counts[1]}</strong><span>Issues</span></div><div className="summary-stat review"><strong>{counts[2]}</strong><span>Needs review</span></div></div>
    <div className="result-layout"><div className="checklist-stack">{Object.entries(sectionTitles).map(([section,title])=>{const sectionItems=current.items.filter((i)=>i.section===section);const isOpen=openSections.includes(section);return <section className="checklist-section" key={section}><button className="section-toggle" onClick={()=>setOpenSections(isOpen?openSections.filter((s)=>s!==section):[...openSections,section])}><span className="section-letter">{section}</span><span><strong>{title}</strong><small>{sectionItems.filter((i)=>i.autoResult==='Yes').length} passed · {sectionItems.length} items</small></span><ChevronDown className={isOpen?'rotate':''}/></button>{isOpen&&<div className="review-items">{sectionItems.map((reviewItem)=><article className="review-item" key={reviewItem.itemCode}><div className={`result-icon ${slug(reviewItem.reviewerResult||reviewItem.autoResult)}`}>{(reviewItem.reviewerResult||reviewItem.autoResult)==='Yes'?<Check/>:(reviewItem.reviewerResult||reviewItem.autoResult)==='No'?<X/>:'!'}</div><div className="review-copy"><span className="item-code">{reviewItem.itemCode}</span><h3>{reviewItem.itemDescription}</h3><p>{reviewItem.evidence}</p>{reviewItem.comment&&<small>{reviewItem.comment}</small>}</div><label className="override"><span>Reviewer result</span><select value={reviewItem.reviewerResult||reviewItem.autoResult} onChange={(e)=>updateItem(reviewItem.itemCode,e.target.value as ItemResult)}><option>Yes</option><option>No</option><option>Needs Review</option></select></label></article>)}</div>}</section>})}</div><aside className="sticky-summary"><h3>Abstract overview</h3><div><span>English</span><strong>{current.englishWordCount} words</strong></div><div><span>Bahasa Melayu</span><strong>{current.malayWordCount} words</strong></div><div><span>Thesis language</span><strong>{current.submission.thesisLanguage}</strong></div><hr/><p><ShieldCheck size={17}/> Automatic results are preliminary. Confirm every judgment-based item.</p></aside></div>
  </div>;
}

function Dashboard() { const {reviews,setCurrent}=useReviews(); const navigate=useNavigate(); const [query,setQuery]=useState(''); const filtered=reviews.filter((r)=>`${r.submission.studentName} ${r.submission.matricNo} ${r.submission.thesisTitle}`.toLowerCase().includes(query.toLowerCase())); const open=(r:ReviewResult)=>{setCurrent(r);navigate('/results')}; return <div className="page"><PageTitle kicker="Registry" title="Review dashboard" text="Track drafts, pre-checks and reviewer decisions saved in this browser." actions={<Link className="button primary" to="/new"><Plus size={17}/> New review</Link>}/><div className="dashboard-cards"><div><span>Total submissions</span><strong>{reviews.length}</strong></div><div><span>Pending decision</span><strong>{reviews.filter((r)=>!r.finalDecision).length}</strong></div><div><span>Accepted</span><strong>{reviews.filter((r)=>r.finalDecision?.startsWith('Acceptable')).length}</strong></div><div><span>Revision required</span><strong>{reviews.filter((r)=>r.finalDecision?.startsWith('Revision')).length}</strong></div></div><section className="table-card"><div className="table-tools"><div><h2>Submissions</h2><p>Local workspace registry</p></div><input aria-label="Search submissions" placeholder="Search student, matric or title…" value={query} onChange={(e)=>setQuery(e.target.value)}/></div>{filtered.length?<div className="table-scroll"><table><thead><tr><th>Submission</th><th>Student</th><th>Programme</th><th>Word count</th><th>Status</th><th/></tr></thead><tbody>{filtered.map((r)=><tr key={r.submission.submissionId}><td><strong>{r.submission.submissionId}</strong><small>{new Date(r.generatedAt).toLocaleDateString()}</small></td><td><strong>{r.submission.studentName}</strong><small>{r.submission.matricNo}</small></td><td>{r.submission.programme}</td><td>EN {r.englishWordCount} · BM {r.malayWordCount}</td><td><span className="table-status">{r.finalDecision||'Pending reviewer decision'}</span></td><td><button className="text-button" onClick={()=>open(r)}>Open →</button></td></tr>)}</tbody></table></div>:<EmptyInline/>}</section></div>; }

function Report() { const {current,setCurrent,refresh}=useReviews(); const [copied,setCopied]=useState(false); const [saving,setSaving]=useState(false); const [saveStatus,setSaveStatus]=useState<{kind:'success'|'warning'|'error';text:string}>(); if(!current)return <EmptyState title="No report to preview" text="Complete a pre-check before preparing a report."/>; const decisions=['Acceptable - No correction required','Acceptable - Minor correction required','Revision required before acceptance'] as const; const save=async()=>{if(!current.finalDecision){setSaveStatus({kind:'error',text:'Select a final decision first.'});return;}if(!current.reviewerName?.trim()){setSaveStatus({kind:'error',text:'Enter the reviewer name first.'});return;}setSaving(true);setSaveStatus(undefined);const local=saveLocalReview(current);setCurrent(local);refresh();const result=await saveReviewerDecision(local);const updated=saveLocalReview({...local,syncWarning:result.warning});setCurrent(updated);refresh();setSaveStatus(result.backendSaved?{kind:'success',text:'Decision saved to Google Sheets.'}:{kind:'warning',text:result.warning!});setSaving(false);}; return <div className="page"><PageTitle kicker="Official record" title="Report preview" text="Confirm the final assessment, then print or save as PDF." actions={<div className="button-row"><button className="button secondary" onClick={async()=>{await copyReportSummary(current);setCopied(true)}}><Copy size={17}/>{copied?'Copied':'Copy summary'}</button><button className="button primary" onClick={()=>window.print()}><Printer size={17}/> Print / PDF</button></div>}/><div className="report-layout"><section className="decision-panel"><h2>Reviewer decision</h2><p>Automated checks do not select this decision.</p><div className="decision-options">{decisions.map((decision)=><label key={decision} className={current.finalDecision===decision?'selected':''}><input type="radio" name="decision" checked={current.finalDecision===decision} onChange={()=>{setCurrent({...current,finalDecision:decision});setSaveStatus(undefined)}}/><span>{decision}</span></label>)}</div><label className="field"><span>Main corrections / comments</span><textarea rows={6} value={current.mainCorrections||''} onChange={(e)=>setCurrent({...current,mainCorrections:e.target.value})}/></label><label className="field"><span>Reviewer name</span><input value={current.reviewerName||''} onChange={(e)=>{setCurrent({...current,reviewerName:e.target.value});setSaveStatus(undefined)}}/></label><button className="button primary full" disabled={saving} onClick={save}><Save size={17}/>{saving?'Saving…':'Save decision'}</button>{saveStatus&&<div className={`save-status ${saveStatus.kind}`} role="status">{saveStatus.text}</div>}</section><ReportPaper review={current}/></div></div>; }

function ReportPaper({review}:{review:ReviewResult}) { return <article className="report-paper"><div className="report-heading"><span><GraduationCap/></span><div><small>Faculty of Computing</small><h1>Thesis Abstract Review Report</h1></div></div><div className="report-meta"><Meta label="Student Name" value={review.submission.studentName}/><Meta label="Matric No." value={review.submission.matricNo}/><Meta label="Programme" value={review.submission.programme}/><Meta label="Date" value={review.submission.reviewDate}/><Meta wide label="Thesis Title" value={review.submission.thesisTitle}/><Meta label="Supervisor" value={review.submission.supervisorName||'—'}/><Meta label="Examiner" value={review.submission.examinerName||'—'}/></div><div className="word-strip"><span>English abstract <strong>{review.englishWordCount} words</strong></span><span>Bahasa Melayu <strong>{review.malayWordCount} words</strong></span></div>{Object.entries(sectionTitles).map(([section,title])=><div className="report-section" key={section}><h2><span>{section}</span>{title}</h2>{review.items.filter((i)=>i.section===section).map((i)=><div className="report-row" key={i.itemCode}><span>{i.itemCode}</span><p>{i.itemDescription}</p><strong className={slug(i.reviewerResult||i.autoResult)}>{i.reviewerResult||i.autoResult}</strong></div>)}</div>)}<div className="report-decision"><h2>Overall assessment</h2><strong>{review.finalDecision||'Pending reviewer decision'}</strong><p>{review.mainCorrections||'No final reviewer comments recorded.'}</p><div className="signature"><span>Reviewer: {review.reviewerName||'____________________'}</span><span>Date: {review.submission.reviewDate}</span></div></div></article>; }
function Meta({label,value,wide=false}:{label:string,value:string,wide?:boolean}){return <div className={wide?'wide':''}><small>{label}</small><strong>{value}</strong></div>}

function SettingsPage(){return <div className="page narrow"><PageTitle kicker="Configuration" title="Settings" text="Connect the production Google Apps Script API without exposing credentials."/><section className="form-section settings-card"><h2>Backend connection</h2><p>This build uses browser storage when <code>VITE_APPS_SCRIPT_URL</code> is empty. Add the deployed Apps Script Web App URL to a local <code>.env</code> file, then rebuild.</p><div className="config-line"><span>Apps Script endpoint</span><strong>{import.meta.env.VITE_APPS_SCRIPT_URL?'Configured':'Local mode'}</strong></div><div className="notice"><ShieldCheck/><p>AI keys and reviewer passcodes belong in Apps Script Properties Service—never in this frontend.</p></div></section></div>}
function Help(){return <div className="page narrow"><PageTitle kicker="Guidance" title="How the review works" text="A structured aid for students, supervisors and examiners."/><div className="help-grid"><Feature icon={<span>1</span>} title="Enter both versions" text="Add thesis details, English abstract and Bahasa Melayu abstract."/><Feature icon={<span>2</span>} title="Run the pre-check" text="The browser evaluates reliable rule-based requirements immediately."/><Feature icon={<span>3</span>} title="Confirm the checklist" text="A reviewer validates uncertain academic, language and alignment judgments."/><Feature icon={<span>4</span>} title="Issue the report" text="Choose an official assessment and print or save the report as PDF."/></div><section className="notice large"><BookOpen/><div><strong>Faculty source documents</strong><p>Rules follow Thesis Abstract Guidelines FC Version 1.0 and the Thesis Abstract Review Checklist. When automation is uncertain, the result is “Needs Review”.</p></div></section></div>}

function EmptyState({title,text}:{title:string,text:string}){return <div className="empty-state"><span><FileText/></span><h1>{title}</h1><p>{text}</p><Link className="button primary" to="/new">Start new review</Link></div>}
function EmptyInline(){return <div className="empty-inline"><FileText/><h3>No submissions found</h3><p>Start a new review to populate the registry.</p></div>}
const slug=(value:string)=>value.toLowerCase().replaceAll(' ','-');
export default App;
